name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget -O - https://tools.azisaba.net/pack.sh | bash -s binary
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: binary
  dispatch:
    name: Dispatch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: AzisabaNetwork/packs.azisaba.net
          event-type: updated
