name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: find . -mindepth 2 -maxdepth 2 -type f -iname pack.mcmeta -print0 | xargs -0 dirname -z | parallel -0 cd {} '&&' zip -r "$PWD"/{/}.zip .
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: アジ鯖リソースパック v${{ github.run_number }}
          body: |-
            リソースパック(テクスチャ)を今すぐダウンロードできます。
            ダウンロードしたいリソースパックを選択してください。
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
