name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: インストール
        run: |
          sudo apt-get -y update
          sudo apt-get -y install moreutils

      - name: zipファイル作成
        run: |
          parallel -v $'cd {} && zip -r '"$PWD"$'/{/}.zip .' ::: packs/*
          parallel -j 1 -v $'jq \'. + [ { "filename": "{/}.zip", "sha1": "\'"$(sha1sum {/}.zip | cut -d \' \' -f 1)"\'", "description": "\'"$(jq -r \'.pack.description\' {}/pack.mcmeta)"\'", "format": "\'"$(jq -r \'.pack.pack_format\' {}/pack.mcmeta)"\'" } ]\' packs.json | sponge packs.json' ::: packs/*

      - name: コミット
        run: |
          git config --local user.email "user@example.com"
          git config --local user.name "GitHub Actions"
          git rm -rq packs
          git add -A
          git commit -m "デプロイ"

      - name: デプロイ
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy
          force: true
