name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - run: bash pack.sh
      - run: git config --local user.name "github-actions[bot]"
      - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add -A
      - run: git commit -m "Deploy" || true
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
