name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - name: インストール
        run: |
          sudo apt-get -y update
          sudo apt-get -y install moreutils

      - name: zipファイル作成
        run: |
          parallel -v zip -r {/}.zip {} ::: packs/*
          parallel -v jq '. + [ { "filename": "{}" } ]' packs.json '|' sponge packs.json ::: *.zip

      - name: コミット
        run: |
          git config --local user.email "user@example.com"
          git config --local user.name "GitHub Actions"
          git rm -rq packs
          git add -A
          git commit -m "デプロイ"

      - name: デプロイ
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: deploy
          force: true
